---
title: "p8105_hw3_rd3097"
author: "RUOYING DENG"
date: "2023-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Necessary Library
```{r}
library(p8105.datasets)
library(dplyr)
#install.packages('cowplot')
library(ggplot2)
library(tidyverse)
library(cowplot)
```


```{r}

data("instacart")

# 1）
instacart %>%
  count(aisle) %>%
  arrange(desc(n))

#There are   
# 2)
df_Q1_2 <- instacart %>%
  count(aisle) %>%
  filter(n > 10000) %>%
  arrange(desc(n))

ggplot(data = df_Q1_2, aes(x = aisle, y= n, group = 1)) +
  geom_line()+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# 3)

instacart %>%
  filter(aisle %in% c('baking ingredients', 'dog food care', 'packaged vegetables fruits')) %>%
  group_by(aisle) %>%
  count(product_name, sort = TRUE) %>%
  top_n(3)
# To ensure the dataset has distinct product name for each order on rows level 
instacart %>%
  group_by(order_id) %>%
  count(product_name) %>%
  ungroup(order_id) %>%
  arrange(desc(n))
  

# 4)
# dow 0-6; hourly 0-23; productName = coffee ice cream, pink....
instacart %>%
  filter(product_name %in% c('Coffee Ice Cream', 'Pink Lady Apples')) %>%
  group_by(product_name,order_dow) %>%
  summarize(Mean = mean(order_hour_of_day, na.rm = TRUE)) %>%
  pivot_wider(names_from = order_dow, values_from = Mean)

```




## Problem 2

```{r}
data("brfss_smart2010")

# Focus Overall Health only

df_Q2 <- brfss_smart2010 %>%
  filter(Topic == 'Overall Health')%>%
  group_by(Response) %>%
  mutate(Response = factor(Response, levels = c('Poor', 'Fair', 'Good', 'Very good', 'Excellent'))) %>%
  ungroup(Response)

# 1)
head(df_Q2) # Locationabbr: states

# 2002 How many states .....
df_Q2 %>%
  filter(Year == 2002) %>%
  group_by(Locationabbr) %>%
  summarize(locationDistinctCount = n_distinct(Locationdesc)) %>%
  filter(locationDistinctCount >=7)

# 2010
df_Q2 %>%
  filter(Year == 2010) %>%
  group_by(Locationabbr) %>%
  summarize(locationDistinctCount = n_distinct(Locationdesc)) %>%
  filter(locationDistinctCount >=7)

# Construct a dataset that is limited to Excellent responses, and contains, year, state, and a variable that averages the data_value across locations within a state. Make a “spaghetti” plot of this average value over time within a state (that is, make a plot showing a line for each state across years – the geom_line geometry and group aesthetic will help)

df_Q2_lineplot <- df_Q2 %>%
  filter(Response == 'Excellent') %>%
  select(Year, Locationabbr, Data_value) %>%
  group_by(Year, Locationabbr) %>%
  summarize(Data_value = mean(Data_value, na.rm = TRUE)) %>%
  ungroup(Year, Locationabbr)

ggplot(data = df_Q2_lineplot, aes(x = Year, y = Data_value)) +
  geom_line(aes(color = Locationabbr))



# Make a two-panel plot showing, for the years 2006, and 2010, distribution of data_value for responses (“Poor” to “Excellent”) among locations in NY State.

df_Q2_2006 <- df_Q2 %>%
  filter(Locationabbr == 'NY' & Year == 2006)

df_Q2_2010 <- df_Q2 %>%
  filter(Locationabbr == 'NY' & Year == 2010) 

Q2Plot1 <- ggplot(df_Q2_2006, aes(x = Response, y = Data_value)) +
  geom_bar(stat = 'summary', fun = 'mean') +
  labs(title = "2006 Distribution of data_value for response")
Q2Plot2 <- ggplot(df_Q2_2010, aes(x = Response, y = Data_value)) +
  geom_bar(stat = 'summary', fun = 'mean') +
  labs(title = "2010 Distribution of data_value for response")


plot_grid(Q2Plot1, Q2Plot2, align = "v", ncol = 1, rel_heights = c(.5, .5))



```

## Problem 3
```{r}
#include all originally observed variables
covar <- read.csv("nhanes_covar.csv",skip =4)
accel <-read.csv("nhanes_accel.csv")
covar %>%
  #exclude participants less than 21 years of age
  filter(age >= 21)%>%
  #exclude those with missing demographic data
  drop_na(BMI, education)%>%
  #encode data with reasonable variable classes in factor instead of numerical
  mutate(sex = factor(recode(sex, "1" = "male", "2" = "female"), levels =c("male", "female")),
           education = factor(recode(education, "1"="Less than high school", "2" = "High school equivalent", "3" = "More than high school"),levels = c("Less than high school","High school equivalent", "More than high school")))

```

